name: WordPress CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    # https://github.com/actions/cache/blob/master/examples.md#php---composer
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      id: composer
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run type check
      if: always()
      run: composer run-script check -- --report=psalm-report.json

    - uses: beaucollins/psalm-annotations-action@v1
      if: always()
      with:
        report_path: ./psalm-report.json
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
